Repository jenkins-x/jenkins-x-builders, pull requests merged in 2018-12, with the labels that each got.

#138 chore: removed unused files causing confusion
  builder-base/.updatebot.yml
  builder-base/release.sh
  builder-maven-32/.updatebot.yml
  builder-maven-32/release.sh
  builder-maven-java11/.updatebot.yml
  builder-maven-java11/release.sh
  builder-maven/.updatebot.yml
  builder-maven/release.sh
Labels: approved, size/L

#141 Add Python 3.7.1 builder
  builder-python37/Dockerfile
  jx-docker-build.sh
Labels: approved, lgtm, ok-to-test, size/S

#164 feat: pushing PR builds to docker hub
  Jenkinsfile
Labels: approved, size/XS

#177 upgrade helm
  Dockerfile.common
Labels: approved, size/XS

#181 feat: upgrade to go 1.11.4
  builder-go/Dockerfile
Labels: approved, size/XS

#186 Added Maven+NodeJS image
  builder-maven-nodejs/Dockerfile
  jx-docker-build.sh
Labels: approved, ok-to-test, size/S
