Repository jenkins-x/jenkins-x-builders, pull requests merged in 2018-10, with the labels that each got.

#1 Updated readme
  Jenkinsfile
  Makefile
  README.md
  builder-base/Dockerfile.php
  builder-base/Dockerfile.slim
  builder-base/build.sh
  jx-docker-build.sh
Labels: size/M

#2 Extract JX_VERSION out as common variable
  Dockerfile.common
  builder-base/Dockerfile.common
  builder-base/build.sh
Labels: size/XS

#3 Added dummy makefile to set version
  Makefile
Labels: size/XS

#4 Commented out failing hugo build
  builder-go/Dockerfile
  jx-docker-build.sh
Labels: size/S

#5 Added dummy dockerfile
  Dockerfile
Labels: size/XS

#6 update JX_VERSION to 1.3.393
  Dockerfile.common
Labels: size/XS, updatebot

#8 feat: enabling pushing of images for each release
  Jenkinsfile
  jx-docker-build.sh
Labels: size/XS

#9 fix: correctly passing in release arg to enable tagging
  Jenkinsfile
Labels: size/XS

#10 fix: enabled downstream updating of jenkins-x-platform
  .updatebot.yml
  jx-docker-build.sh
Labels: size/S

#11 fix: updated downstream builder for helm values
  .gitignore
  jx-docker-build.sh
Labels: size/XS

#12 fix: reenabled hugo build
  builder-go/Dockerfile
Labels: size/S

#15 Add newman builder
  builder-newman/Dockerfile
  builder-newman/README.md
  jx-docker-build.sh
Labels: approved, size/S

#26 fix: displaying all build output
  jx-docker-build.sh
Labels: size/XS

#28 fix: ensuring all build output is logged
  builder-base/build.sh
Labels: approved, size/XS

#30 fix: reordered docker push commands
  jx-docker-build.sh
Labels: approved, size/M

#20 Added Java 11 builder
  builder-maven-java11/.updatebot.yml
  builder-maven-java11/Dockerfile
  builder-maven-java11/release.sh
Labels: approved, size/M

#47 feat: upgrade gcloud to 222.0.0
  Dockerfile.common
Labels: approved, size/XS

#50 feat: jx-build-templates are now downstream of this repo
  .updatebot.yml
  jx-docker-build.sh
Labels: approved, size/XS
