Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-12, with the labels that each got.

#1066 feat: add builder for asciidoctor
  builder-asciidoctor/Dockerfile
  builder-asciidoctor/test/container-test.yaml
  jenkins-x.yml
Labels: approved, size/M

#1067 fix: add nodejs asciidoctor builder, for antra
  builder-asciidoctor/Dockerfile
Labels: approved, lgtm, size/S

#1074 fix: build python37 with SQLite3 support
  builder-python37/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS
