Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-01, with the labels that each got.

#187 Added IntelliJ to Git ignore
  .gitignore
Labels: approved, lgtm, ok-to-test, size/XS

#189 chore: upgrade skaffold to 0.20.0
  Dockerfile.common
Labels: approved, size/XS

#192 Add new version specific gradle and nodejs images
  builder-gradle4/Dockerfile
  builder-gradle4/set_java
  builder-gradle5/Dockerfile
  builder-gradle5/set_java
  builder-nodejs10x/Dockerfile
  builder-nodejs8x/Dockerfile
  jx-docker-build.sh
Labels: approved, lgtm, ok-to-test, size/L

#217 upgrade helm
  Dockerfile.common
Labels: approved, size/XS

#212 Let builder-nodejs use node 11.x
  builder-nodejs/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#230 feat(latest) attempting to push :latest on release build
  builder-base/build.sh
  jx-docker-build.sh
Labels: approved, size/M

#235 Upgraded base image and JDK for Java 11
  builder-maven-java11/Dockerfile
Labels: approved, ok-to-test, size/XS

#239 Replaced Java8's doclet with Java11's
  builder-maven-java11/Dockerfile
Labels: approved, ok-to-test, size/XS
