Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-07, with the labels that each got.

#532 chore: Update dependencies to include pytorch 1.1.0 and onnx 1.5.0
  builder-machine-learning-gpu/Dockerfile
Labels: needs-ok-to-test, size/XS

#554 feat: only running changelog on release if the sha is set
  changelog.sh
Labels: approved, size/XS

#557 fix: Update builder-jx in jenkins-x-platform
  update-bot.sh
Labels: approved, lgtm, size/XS

#556 chore: switch to new updatebot
  update-bot.sh
Labels: approved, lgtm, size/M

#566 chore: Disabling building and updating of ML builders for now.
  jenkins-x.yml
  update-bot.sh
Labels: approved, lgtm, size/M

#562 chore: add memory request/limits
  jenkins-x.yml
Labels: approved, lgtm, size/S

#578 chore: Stop using just-generated builders as base images
  Dockerfile.gobase
  Dockerfile.mavenbase
  builder-go-maven/Dockerfile
  builder-go/Dockerfile
  builder-maven-java11/Dockerfile
  builder-maven-nodejs/Dockerfile
  builder-maven/Dockerfile
  builder-terraform/Dockerfile
  replace-versions.sh
Labels: approved, lgtm, size/L

#572 chore: Updating OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#583 fix: One `jx step create pr chart` call for all of jenkins-x-platform
  jenkins-x.yml
  update-bot.sh
Labels: approved, lgtm, size/M

#595 chore: added precommit configuration
  .pre-commit-config.yaml
  .secrets.baseline
Labels: approved, lgtm, size/M

#608 feat: Run just the PR build in parallel
  jenkins-x.yml
Labels: approved, lgtm, size/XL
