Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-11, with the labels that each got.

#954 chore: Update Terraform and Terragrunt
  builder-terraform/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#967 chore: Add `builder-go-nodejs` for UI tests in BDD tests
  builder-go-nodejs/Dockerfile
  jenkins-x.yml
  replace-versions.sh
  update-bot.sh
Labels: approved, size/M

#996 Add dotnet builder
  builder-dotnet/Dockerfile
  jenkins-x.yml
Labels: approved, lgtm, ok-to-test, size/S

#1028 chore: Add builder-dotnet to updatebot
  update-bot.sh
Labels: approved, size/XS

#1014 chore: maven 3.6.2 -> maven 3.6.3
  Dockerfile.mavenbase
  builder-go-maven/Dockerfile
  builder-maven-32/Dockerfile
  builder-maven-graalvm/Dockerfile
  builder-maven/Dockerfile
Labels: approved, ok-to-test, size/S
