Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-08, with the labels that each got.

#653 chore: remove chart pr for env controller
  update-bot.sh
Labels: approved, lgtm, size/XS

#658 fix: Move updatebot and release notes into a separate stage
  jenkins-x.yml
Labels: size/S

#659 chore: Cut down parallelism, try to get them to run on different nodes
  jenkins-x.yml
Labels: approved, lgtm, size/L
