Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-03, with the labels that each got.

#256 Upgraded Go version
  builder-go/Dockerfile
Labels: approved, ok-to-test, size/XS

#282 Removed unnecessary packages from newman builder image dockerfile.
  builder-newman/Dockerfile
Labels: approved, lgtm, ok-to-test, size/S

#281 Created builder images for awscli and awscli-local
  builder-awscli-local/Dockerfile
  builder-awscli-local/skaffold.yaml
  builder-awscli/Dockerfile
  builder-awscli/skaffold.yaml
Labels: approved, lgtm, ok-to-test, size/M

#308 fix updatebot step image
  jenkins-x.yml
Labels: approved, size/XS

#309 add missing nodejs image
  jenkins-x.yml
Labels: approved, size/S

#312 avoid builder-base version upgrade as its not in this repo anymore
  update-bot.sh
Labels: approved, size/XS

#314 fix: update builder base
  builder-dlang/Dockerfile
  builder-dotnet/Dockerfile
  builder-go/Dockerfile
  builder-gradle/Dockerfile
  builder-gradle4/Dockerfile
  builder-gradle5/Dockerfile
  builder-jx/Dockerfile
  builder-maven-32/Dockerfile
  builder-maven-java11/Dockerfile
  builder-maven/Dockerfile
  builder-newman/Dockerfile
  builder-nodejs/Dockerfile
  builder-nodejs10x/Dockerfile
  builder-nodejs8x/Dockerfile
  builder-python/Dockerfile
  builder-python2/Dockerfile
  builder-python37/Dockerfile
  builder-rust/Dockerfile
  builder-scala/Dockerfile
  builder-terraform/Dockerfile
  jenkins-x.yml
Labels: size/M

#322 fix: updatebot container uses java8 rather 11
  jenkins-x.yml
Labels: approved, size/XS

#323 update JX_VERSION to 1.3.992
  builder-dlang/Dockerfile
  builder-dotnet/Dockerfile
  builder-go-maven/Dockerfile
  builder-go/Dockerfile
  builder-gradle/Dockerfile
  builder-gradle4/Dockerfile
  builder-gradle5/Dockerfile
  builder-jx/Dockerfile
  builder-maven-32/Dockerfile
  builder-maven-java11/Dockerfile
  builder-maven/Dockerfile
  builder-newman/Dockerfile
  builder-nodejs/Dockerfile
  builder-nodejs10x/Dockerfile
  builder-nodejs8x/Dockerfile
  builder-python/Dockerfile
  builder-python2/Dockerfile
  builder-python37/Dockerfile
  builder-ruby/Dockerfile
  builder-rust/Dockerfile
  builder-scala/Dockerfile
  builder-swift/Dockerfile
  builder-terraform/Dockerfile
Labels: size/M, updatebot

#324 feat: reenabled swift / ruby image builds
  jenkins-x.yml
Labels: approved, size/M

#320 feat: re-added in builds for aws builders
  builder-python37/Dockerfile
  replace-versions.sh
  update-bot.sh
Labels: approved, size/XS

#365 feat: change how 32bit java images are built
  builder-dlang/Dockerfile
  builder-dotnet/Dockerfile
  builder-go-maven/Dockerfile
  builder-go-maven/set_java
  builder-go/Dockerfile
  builder-gradle/Dockerfile
  builder-gradle/set_java
  builder-gradle4/Dockerfile
  builder-gradle4/set_java
  builder-gradle5/Dockerfile
  builder-gradle5/set_java
  builder-jx/Dockerfile
  builder-maven-32/Dockerfile
  builder-maven-java11/Dockerfile
  builder-maven/Dockerfile
  builder-newman/Dockerfile
  builder-nodejs/Dockerfile
  builder-nodejs10x/Dockerfile
  builder-nodejs8x/Dockerfile
  builder-python/Dockerfile
  builder-python2/Dockerfile
  builder-python37/Dockerfile
  builder-ruby/Dockerfile
  builder-rust/Dockerfile
  builder-scala/Dockerfile
  builder-swift/Dockerfile
  builder-terraform/Dockerfile
  jenkins-x.yml
Labels: approved, size/L

#367 feat: revert builder-go-maven to 32bit jvm
  builder-go-maven/Dockerfile
  builder-go-maven/set_java
  jenkins-x.yml
Labels: approved, size/S
