Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-02, with the labels that each got.

#233 Update skaffold to v0.21.1
  Dockerfile.common
  builder-base/Dockerfile.common
Labels: approved, size/XS

#183 feat: attempting to use skaffold / gcb to build images
  .gitignore
  builder-base/Dockerfile.apt
  builder-base/Dockerfile.php
  builder-base/Dockerfile.ruby
  builder-base/Dockerfile.slim
  builder-base/Dockerfile.slim.commands
  builder-base/Dockerfile.swift
  builder-base/build.sh
  builder-base/skaffold.yaml
  builder-dlang/skaffold.yaml
  builder-dotnet/Dockerfile
  builder-dotnet/skaffold.yaml
  builder-go-maven/skaffold.yaml
  builder-go/Dockerfile
  builder-go/skaffold.yaml
  builder-gradle/skaffold.yaml
  builder-gradle4/skaffold.yaml
  builder-gradle5/skaffold.yaml
  builder-maven-32/skaffold.yaml
  builder-maven-java11/Dockerfile
  builder-maven-java11/skaffold.yaml
  builder-maven-nodejs/skaffold.yaml
  builder-maven/skaffold.yaml
  builder-newman/Dockerfile
  builder-newman/skaffold.yaml
  builder-nodejs/skaffold.yaml
  builder-nodejs10x/skaffold.yaml
  builder-nodejs8x/skaffold.yaml
  builder-python/skaffold.yaml
  builder-python2/skaffold.yaml
  builder-python37/skaffold.yaml
  builder-rust/skaffold.yaml
  builder-scala/skaffold.yaml
  builder-terraform/skaffold.yaml
  jx-docker-build.sh
Labels: approved, size/XXL

#242 Added AWS CDK builder image
  builder-aws-cdk/Dockerfile
  jx-docker-build.sh
Labels: approved, ok-to-test, size/XS

#131 chore Base cleanup
  builder-base/Dockerfile
  builder-base/Dockerfile.slim.commands
Labels: approved, size/L

#259 feat: attempting to add caching to skaffold
  builder-aws-cdk/skaffold.yaml
  builder-base/build.sh
  builder-base/skaffold.yaml
  builder-dlang/skaffold.yaml
  builder-dotnet/skaffold.yaml
  builder-go-maven/skaffold.yaml
  builder-go/skaffold.yaml
  builder-gradle/skaffold.yaml
  builder-gradle4/skaffold.yaml
  builder-gradle5/skaffold.yaml
  builder-maven-32/skaffold.yaml
  builder-maven-java11/skaffold.yaml
  builder-maven-nodejs/skaffold.yaml
  builder-maven/skaffold.yaml
  builder-newman/skaffold.yaml
  builder-nodejs/skaffold.yaml
  builder-nodejs10x/skaffold.yaml
  builder-nodejs8x/skaffold.yaml
  builder-python/skaffold.yaml
  builder-python2/skaffold.yaml
  builder-python37/skaffold.yaml
  builder-rust/skaffold.yaml
  builder-scala/skaffold.yaml
  builder-terraform/skaffold.yaml
Labels: approved, size/L

#261 fix: increased timeout for builder base
  builder-base/skaffold.yaml
Labels: approved, size/XS

#264 fix: attempting to simplify build using parent image
  builder-base/Dockerfile
  builder-base/Dockerfile.slim.commands
  builder-base/Dockerfile.yum
  builder-base/build.sh
  builder-base/skaffold.yaml
  builder-go-maven/Dockerfile
  builder-go/Dockerfile
  builder-gradle/Dockerfile
  builder-gradle4/Dockerfile
  builder-gradle5/Dockerfile
  builder-python2/Dockerfile
  builder-python37/Dockerfile
  jx-docker-build.sh
Labels: approved, size/L

#252 fix(helm): use the right tiller version
  builder-base/Dockerfile.common
Labels: approved, lgtm, ok-to-test, size/XS

#254 Add dep as dependency manager
  builder-go/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#270 feat: POC adding new ruby / swift base images
  builder-base/Dockerfile
  builder-base/Dockerfile.apt
  builder-base/Dockerfile.rubybase
  builder-base/Dockerfile.swiftbase
  builder-base/build.sh
Labels: approved, size/M

#271 feat: attempting to cleanup images to reduce size
  builder-dlang/Dockerfile
  builder-dotnet/Dockerfile
  builder-go/Dockerfile
  builder-newman/Dockerfile
  builder-nodejs/Dockerfile
  builder-nodejs10x/Dockerfile
  builder-nodejs8x/Dockerfile
  builder-python/Dockerfile
  builder-python2/Dockerfile
  builder-python37/Dockerfile
  builder-rust/Dockerfile
  builder-scala/Dockerfile
Labels: approved, size/M

#275 Update Dockerfile.common
  Dockerfile.common
Labels: approved, ok-to-test, size/XS
