Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-04, with the labels that each got.

#377 feat: using kaniko secret
  jenkins-x.yml
Labels: approved, size/S

#378 feat: remove unused skaffold.yaml
  builder-dlang/skaffold.yaml
  builder-dotnet/skaffold.yaml
  builder-go-maven/skaffold.yaml
  builder-go/skaffold.yaml
  builder-gradle/skaffold.yaml
  builder-gradle4/skaffold.yaml
  builder-gradle5/skaffold.yaml
  builder-jx/skaffold.yaml
  builder-maven-32/skaffold.yaml
  builder-maven-java11/skaffold.yaml
  builder-maven-nodejs/skaffold.yaml
  builder-maven/skaffold.yaml
  builder-newman/skaffold.yaml
  builder-nodejs/skaffold.yaml
  builder-nodejs10x/skaffold.yaml
  builder-nodejs8x/skaffold.yaml
  builder-python/skaffold.yaml
  builder-python2/skaffold.yaml
  builder-python37/skaffold.yaml
  builder-rust/skaffold.yaml
  builder-scala/skaffold.yaml
  builder-terraform/skaffold.yaml
Labels: approved, size/XL

#376 added jdk11 support, removed android SDK due to current incompatibili…
  builder-gradle5-java11/Dockerfile
  builder-gradle5-java11/test/container-test.yaml
  jenkins-x.yml
Labels: approved, lgtm, ok-to-test, size/M

#382 Changed the downloaded version from setup_11 to setup_8
  builder-nodejs8x/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#385 feat: switching to /workspace/source to workspace dir
  jenkins-x.yml
Labels: approved, size/L

#387 fix: make container names unique
  jenkins-x.yml
Labels: size/XS

#395 chore(go): update Go version to 1.12.4
  builder-go/Dockerfile
Labels: approved, ok-to-test, size/XS

#390 Fix typo for nodejs10x docker image
  jenkins-x.yml
Labels: approved, ok-to-test, size/XS

#409 feat: Added machine-learning builder
  builder-machine-learning/Dockerfile
  builder-machine-learning/test/container-test.yaml
  jenkins-x.yml
Labels: approved, ok-to-test, size/M

#421 feat: added builder with cf-cli
  builder-cf/Dockerfile
  jenkins-x.yml
Labels: approved, size/M

#425 fix: corrected invalid base images to speed build
  builder-cf/Dockerfile
  builder-machine-learning/Dockerfile
Labels: approved, size/XS
