Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-09, with the labels that each got.

#702 fix: push the 'latest' image on release
  jenkins-x.yml
Labels: approved, lgtm, size/M

#724 chore: bumped Hugo from 0.49 to 0.58.0/extended
  Dockerfile.gobase
Labels: approved, lgtm, size/S

#657 chore(deps): bump maven from 3.5.2 to 3.6.1
  Dockerfile.mavenbase
Labels: approved, lgtm, ok-to-test, size/XS

#656 chore(deps): bump gradle from 5.1 to 5.6
  builder-gradle5-java11/Dockerfile
  builder-gradle5/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#733 chore: gradle 5.6.2
  builder-gradle5-java11/Dockerfile
  builder-gradle5/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#732 chore: Maven 3.6.2
  Dockerfile.mavenbase
  builder-go-maven/Dockerfile
  builder-maven-32/Dockerfile
  builder-maven-graalvm/Dockerfile
  builder-maven/Dockerfile
Labels: approved, lgtm, ok-to-test, size/S

#616 chore(deps): bump Scala 2.12.9 and SBT 1.2.8
  builder-scala/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#725 feat: adding node12x builder
  builder-nodejs12x/Dockerfile
  builder-nodejs12x/test/container-test.yaml
  builder-php5x/Dockerfile
  builder-php5x/test/container-test.yaml
  builder-php7x/Dockerfile
  builder-php7x/test/container-test.yaml
  jenkins-x.yml
  update-bot.sh
Labels: approved, lgtm, size/L

#756 feat: add updatebot to containers that have java & maven
  builder-go-maven/Dockerfile
  builder-maven-32/Dockerfile
  builder-maven-java11/Dockerfile
  builder-maven-nodejs/Dockerfile
  builder-maven/Dockerfile
Labels: approved, size/M

#812 chore: Clean up dangling downloads/cache/etc in a few places
  Dockerfile.gobase
  Dockerfile.mavenbase
  builder-go-maven/Dockerfile
  builder-gradle/Dockerfile
  builder-gradle4/Dockerfile
  builder-gradle5-java11/Dockerfile
  builder-gradle5/Dockerfile
  builder-maven-32/Dockerfile
  builder-maven/Dockerfile
  builder-nodejs10x/Dockerfile
  builder-nodejs12x/Dockerfile
  builder-php5x/Dockerfile
  builder-php7x/Dockerfile
  builder-python/Dockerfile
  builder-python37/Dockerfile
  builder-rust/Dockerfile
  builder-scala/Dockerfile
Labels: approved, size/L
