Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-05, with the labels that each got.

#427 Updates to Machine Learning builder
  builder-machine-learning/Dockerfile
  update-bot.sh
Labels: approved, ok-to-test, size/XS

#438 chore: change the env variables in the pipeline file to pass the syntax validation
  jenkins-x.yml
Labels: approved, size/XS

#446 Openapi
  builder-maven/Dockerfile
Labels: size/S

#448 fix: correct env var
  builder-maven/Dockerfile
Labels: approved, size/XS

#462 feat: add gotestsumn to builder-go
  builder-go/Dockerfile
Labels: approved, lgtm, size/XS

#465 feat: update terraform to v0.12.0
  builder-terraform/Dockerfile
Labels: approved, size/XS

#467 feat: make terraform builder extend go builder for bdd tests
  builder-go-maven/Dockerfile
  builder-terraform/Dockerfile
  replace-versions.sh
Labels: approved, size/S
