Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-10, with the labels that each got.

#823 fix: Use jx version as basis for release version
  builder-gradle/Dockerfile
  builder-gradle4/Dockerfile
  builder-gradle5/Dockerfile
  jenkins-x.yml
  update-bot.sh
Labels: approved, lgtm, size/L

#817 chore(deps): bump SBT from 1.2.8 to 1.3.2
  builder-scala/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#824 fix: Wrong path for jx in updatebot.sh
  OWNERS
  update-bot.sh
Labels: approved, size/XS

#827 fix: Specify jx.git as source for jx version updates downstream
  update-bot.sh
Labels: approved, lgtm, size/XS

#877 feat: cloudbees/arcalos is downstream of builders
  update-bot.sh
Labels: approved, size/XS

#850 chore(deps): bump Terraform and Terragrunt versions
  builder-terraform/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#904 feat: Updated graal to current version, added native-image build tools
  builder-maven-graalvm/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#925 fix: add PRs for tenant service
  update-bot.sh
Labels: size/XS

#934 fix: update-bot.sh execution needs go now
  jenkins-x.yml
Labels: approved, lgtm, size/XS
