Repository jenkins-x/jenkins-x-builders, pull requests merged in 2019-06, with the labels that each got.

#478 GraalVM builder
  builder-maven-graalvm/Dockerfile
  jenkins-x.yml
  update-bot.sh
Labels: approved, size/M

#495 chore: add release notes
  changelog.sh
  docs/dev/changelog-footer.md
  docs/dev/changelog-header.md
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#510 Upgrade Terragrunt to 0.19.4
  builder-terraform/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#512 feat: Add builder for training Machine Learning projects using CUDA
  builder-machine-learning-gpu/Dockerfile
  builder-machine-learning-gpu/test/container-test.yaml
  jenkins-x.yml
  update-bot.sh
Labels: approved, lgtm, ok-to-test, size/M
