Repository jenkins-x/jenkins-x-builders, pull requests merged in 2020-06, with the labels that each got.

#1340 fix: Switch go.mod updatebot to semver
  update-bot.sh
Labels: approved, lgtm, size/XS

#1348 feat: builder for maven-java14
  builder-maven-java14/Dockerfile
  jenkins-x.yml
  update-bot.sh
Labels: approved, lgtm, ok-to-test, size/M

#1299 chore: add maven graalvm builder for java 11
  builder-maven-graalvm-java11/Dockerfile
  jenkins-x.yml
  update-bot.sh
Labels: approved, ok-to-test, size/M
