Repository jenkins-x/jenkins-x-builders, pull requests merged in 2020-05, with the labels that each got.

#1287 chore(deps): bump sbt to 1.3.10
  builder-scala/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#1250 chore: Switch from go 1.12.16 to 1.13.8.
  Dockerfile.gobase
Labels: approved, lgtm, size/XS

#1300 chore: bump graalvm version to 20.0.0
  builder-maven-graalvm/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#1305 fix: Update node to 10.x
  builder-newman/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#1319 chore: remove use of jx step credential
  jenkins-x.yml
Labels: approved, lgtm, size/L
