Repository jenkins-x/jenkins-x-builders, pull requests merged in 2020-04, with the labels that each got.

#1244 chore: Pin warmer image tag
  jenkins-x.yml
Labels: approved, lgtm, size/S

#1245 chore: sbt 1.3.9
  builder-scala/Dockerfile
Labels: approved, ok-to-test, size/XS

#1266 chore: remove unused updatebot PRs to arcalos repo
  update-bot.sh
Labels: approved, lgtm, size/XS
