Repository jenkins-x/jenkins-x-builders, pull requests merged in 2020-07, with the labels that each got.

#1364 chore: remove downstream builds on arcalos
  update-bot.sh
Labels: approved, lgtm, size/XS

#1354 Node 14 builder
  builder-nodejs14x/Dockerfile
  builder-nodejs14x/test/container-test.yaml
  jenkins-x.yml
  update-bot.sh
Labels: approved, lgtm, ok-to-test, size/M

#1370 fix: Fix input parameters for Tekton 0.11
  jenkins-x.yml
Labels: approved, size/L
